apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: posthere-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Arshdeepdubey/Posthere
    targetRevision: devops/argocd-k8s-deployment
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: posthere
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
